<!-- Common Pop-up controls for all pages -->
<style>
        .video-play {
            height: 100px;
            left: 40%;
            top: 40%;
            width: 100px;
        }
</style>
   <div id="myShare" class="reveal-modal xlarge">
       <div class="row popupwindow">
           <div class="large-9 small-9 column popupwindow_margin">
               <ul class="popupwindow">
                   <li>Share this 
                   </li>
                   <li>
                       <ul>

                           <li>
                               <a href="javascript:" onclick="ShareMessage('F',this);">
                                   <div class="popupwindow_img ">
                                       <img src="foundation/Images/fb_icon_2.png" alt="Facebook icon">
                                   </div>
                                  Post on Facebook</a></li>
                           <li>
                               <a href="javascript:" onclick="ShareMessage('T',this);">
                                   <div class="popupwindow_img">
                                       <img src="foundation/Images/twitter_icon_2.png" alt="twitter icon">
                                   </div>
                                   Tweet on Twitter</a></li>
                           <li>
                               <a href="javascript:" onclick="ShareMessage('G', this);">
                                   <div class="popupwindow_img">
                                       <img src="foundation/Images/google_icon_2.png" alt="google icon">
                                   </div>
                                   Post on Google+</a></li>
                           <li>
                               <a href="mailto:?subject=Your friend thought you might be interested...&amp;body=&lt;div style=&#39;padding: 0;&#39;&gt;    &lt;div style=&#39;padding: 0;&#39;&gt;    &lt;p&gt;I found this on the Benefiber&#174; Website? I think you might find it interesting.  &lt;a href=&#39;@(Request.Url.ToString())&#39; &gt;Click here &lt;/a&gt;&lt;/p&gt;    &lt;p&gt;This email was sent to you by your friend with content generated by Novartis Consumer Health, Inc. Novartis does not keep your email address that was used to generate this email. This email is sent from an account we use for sending messages only.- If you want to contact us, do not reply to this email. Instead call us at 1-800-452-0051. If you believe you have experienced an adverse event when using our product, please contact us at 1-800-452-0051. If you have a medical emergency, contact your doctor immediately. Use as directed.&lt;/p&gt;&lt;/div&gt;&lt;div style=&#39;padding: 0; &gt;    &lt;p style=&#39;padding: 0&#39;&gt;This e-mail was sent by: Novartis Consumer Health, Inc. 200 Kimball Drive, Parsippany, NJ 07054&lt;/p&gt;  &lt;hr/&gt;     &lt;table cellpadding=&#39;0&#39; cellspacing=&#39;0&#39; width=&#39;100%&#39; style=&#39;-webkit-text-size-adjust: none;&#39;&gt;&lt;tr&gt;&lt;td style=&#39;font-size:10px;&#39;&gt;&lt;a href=&#39;http://novartis.dminc.com/Benefiber/pages/termsofuse&#39;&gt;Terms&amp;nbsp;of&amp;nbsp;Use&lt;/a&gt;&amp;nbsp;&amp;nbsp;|&amp;nbsp;&amp;nbsp;&lt;a href=&#39;http://novartis.dminc.com/Benefiber/pages/privacypolicy&#39;&gt;Privacy&amp;nbsp;Policy&lt;/a&gt;&amp;nbsp;&amp;nbsp;|&amp;nbsp;&amp;nbsp;&lt;a href=&#39;http://novartis.dminc.com/Benefiber/pages/contactus&#39;&gt;Contact&amp;nbsp;Us&lt;/a&gt;&lt;/td&gt;&lt;td style=&#39;text-align:right;&#39;&gt;&lt;a href=&#39;http://www.Novartis.com&#39;&gt;&lt;img src=&#39;http://novartis.dminc.com/Benefiber/images/footer_logo.png&#39; width=&#39;80px&#39; height=&#39;15&#39; /&gt;&lt;/a&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;div style=&#39;clear: both&#39;&gt;&lt;/div&gt;&lt;/div&gt;"  >
                                   <div class="popupwindow_img">
                                       <img src="foundation/Images/mail_icon_2.png" alt="mail">
                                   </div>
                                   Share with E-Mail</a></li>
                       </ul>
                   </li>

               </ul>
           </div>
       </div>
       <a class="close-reveal-modal">&#215;</a>
   </div>
   <div id="myConfirm" class="reveal-modal large">
       <div class="row">
           <ul class="disclaimer">
               <li>
                   <p>
                       Clicking on this link means that you have chosen to leave our website. While we believe that the website which you have selected to visit may be of interest to you, it is an independent website which is not under our control. As a result, we do not endorse its content and we have no responsibility for its content or privacy practices. If you do not wish to leave this site, click Cancel. Or, click OK to continue.
                   </p>
                   <div class="action">
                       <input type="submit" id="btnCancel" value="Cancel" class="secondary button disclaimerbutton disclaimerbutton-light" />
                       <input type="submit" id="btnOK" value="Ok" class="secondary button disclaimerbutton " />
                   </div>
               </li>
           </ul>
       </div>
       <a class="close-reveal-modal">&#215;</a>
   </div>
   <div id="videoModal" class="reveal-modal xlarge">
        <div id="VideoTitle" style="">
            <div class="ContainervideoTitle"><span class="videoTitle" id="videoTitle">Video Title</span></div>
            <div id="Close_videoModal" onclick="$('#videoModal').foundation('reveal', 'close');"
                class="CloseReveal">
                &#215;
            </div>
        </div>
        <div class="flex-video">
        </div>
    </div>


<!-- Common Scripts for all pages -->
<script src="./foundation/Scripts/jquery-1.8.2.js"></script>
<script src="./foundation/Scripts/jquery-lazyload.js"></script>
<script src="./foundation/Scripts/foundation/foundation.js"></script>
<script src="./foundation/Scripts/foundation/foundation.interchange.js"></script>
<script src="./foundation/Scripts/foundation/foundation.topbar.js"></script>
<script src="./foundation/Scripts/foundation/app.js"></script>
<script src="./foundation/Scripts/foundation/foundation.reveal.js"></script>
<script src="./foundation/Scripts/foundation/foundation.orbit.js"></script>
<script src="./foundation/Scripts/foundation/foundation.section.js"></script>

    
    <script type="text/javascript">
        $(document).foundation();
        prodlist.push(new  productInfo ('/products/powder'.toLowerCase(), 'Benefiber<sup>®</sup> Powder'));
        $("img.lazy").lazyload();
        siteRootUrl = '';
        $(document).ready(function () {
            // $.each($("a[href^='http']"), function () { $(this).click(function () { OpenLink($(this).attr("href"), $(this)); return false; }); });
            // $.each($("a[href^='http']").not("a[href^='http://www.novartis.com']").not("a[href^='https://www.benefiber.com']"), function () { $(this).click(function () { OpenLink($(this).attr("href"), $(this)); return false; }); });
            updateLinks();
            if (siteRootUrl != null && siteRootUrl != "") {
                $.each($("a[href^='/']").not("[href^='" + siteRootUrl + "']"), function () { $(this).attr("href", siteRootUrl + $(this).attr("href")); });
                $.each($("img[src^='/']").not("[src^='" + siteRootUrl + "']"), function () { $(this).attr("src", siteRootUrl + $(this).attr("src")); });
            }
        });
    </script>
	<script>
        var currentId = 0;
        $(document).ready(function () {
            $("#homePageSlider").on("orbit:after-slide-change", function (event, orbit) {
                currentId = orbit.slide_number;
            });
        });
        var e1;
        window.addEventListener('load', function () {
            var box1 = document.getElementById('topBand')
            // var statusdiv = document.getElementById('statusdiv')
            var startx = 0;
            var dist = 0;
            box1.addEventListener('touchstart', function (e) {
                var touchobj = e.changedTouches[0] // reference first touch point (ie: first finger)
                startx = parseInt(touchobj.clientX) // get x position of touch point relative to left edge of browser
                // statusdiv.innerHTML = 'Status: touchstart<br /> ClientX: ' + startx + 'px'
                e.preventDefault()
            }, false)
            box1.addEventListener('touchmove', function (e) {
                var touchobj = e.changedTouches[0] // reference first touch point for this event
                var dist = parseInt(touchobj.clientX) - startx
                //statusdiv.innerHTML = 'Status: touchmove<br /> Horizontal distance traveled: ' + dist + 'px'
                e.preventDefault()
            }, false)
            box1.addEventListener('touchend', function (e) {
                var touchobj = e.changedTouches[0] // reference first touch point for this event
                //statusdiv.innerHTML = 'Status: touchend<br /> Resting x coordinate: ' + touchobj.clientX + 'px'
                if (Math.abs(startx - touchobj.clientX) > 10)
                    if (startx + 10 < touchobj.clientX)
                        $(".orbit-prev").click();
                    else
                        $(".orbit-next").click();
                else {
                    $("#C" + currentId).click();
                }
                e.preventDefault()
            }, false)

        }, false);
	</script>
		
    
	 <!--  MMM  -->
	      
 	<script type="text/javascript"> 	 	
        $(document).ready(function () {
            resetTab();
        });
        function resetTab() {
            var newWidth = 100 / $("div[data-section='tabs'] > section").length;
            var left = 0;
            $("div[data-section='tabs'] > section").each(function () {
                $(this).find("p.title").css(
                    {
                        "width": newWidth + "%",
                        "left": left + "%",
                        "text-align": "center"
                    }
                );
                left = left + newWidth;
            });
        }
        window.addEventListener('orientationchange', resetTab);
    </script>   
    
    <div class="block-background hide-for-large hide-for-small hide-for-medium hide-for-xlarge"></div>        
	<script type="text/javascript">          /****Omniture tagging starts here!!****/if (typeof (s) !== "undefined") {s.pageName="m.benefiber:us:home"; s.pageType="content/video"; s.channel="m.benefiber:us:home"; s.prop1="home"; s.prop2="home"; s.prop3="content/video"; s.prop4="Benefiber"; s.prop5="US"; s.prop6="EN"; s.prop50="document.URL;"; s.eVar12="Mobile"; s.eVar4="Benefiber"; s.eVar5="US"; s.eVar6="EN"; s.server=document.URL.match("m.benefiber.com") ? "m.benefiber.com" : "Integration"; s.charSet="utf-8"; /************* DO NOT ALTER ANYTHING BELOW THIS LINE !**************/  var s_code = s.t(); if (s_code) document.write(s_code)  } /****Omniture tagging ends here!!****/ /****FloodLight tagging starts here!!****/  floodLightTagging('image','bfibs','benef691');  /****FloodLight tagging ends here!!****/
	</script> 	